spring:
  profiles:
    include: common
  redis:
    host: 192.168.3.235
    port: 6379

logging:
  pattern:
    console: "%d{MM-dd HH:mm:ss.SSS} %contextName [%thread] %-5level %logger{36} - %msg%n"

tjx:
  host: 192.168.3.235

